/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cvcm;
import java.sql.PreparedStatement;
import java.sql.ResultSet;


/**
 *
 * @author kashi
 */
public class CenterJFrame extends javax.swing.JFrame {
ConnectionClass cobj= new ConnectionClass();
    PreparedStatement pst;
    ResultSet rst;
    long CenterID;
    /**
     * Creates new form CenterJFrame
     */
    public CenterJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        AddressjLabel1 = new javax.swing.JLabel();
        PhonejLabel2 = new javax.swing.JLabel();
        EmailjLabel3 = new javax.swing.JLabel();
        InchargeNamejLabel4 = new javax.swing.JLabel();
        TimingsjLabel5 = new javax.swing.JLabel();
        AddressjTextField1 = new javax.swing.JTextField();
        PhonejTextField2 = new javax.swing.JTextField();
        EmailjTextField3 = new javax.swing.JTextField();
        InchargeNamejTextField4 = new javax.swing.JTextField();
        TimingsjTextField5 = new javax.swing.JTextField();
        savejButton1 = new javax.swing.JButton();
        SearchjButton2 = new javax.swing.JButton();
        UpdatejButton3 = new javax.swing.JButton();
        ResetjButton4 = new javax.swing.JButton();
        ErrorjLabel1 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddressjLabel1.setText("Address");

        PhonejLabel2.setText("Phone");

        EmailjLabel3.setText("Email");

        InchargeNamejLabel4.setText("Incharge Name");

        TimingsjLabel5.setText("Timings");

        AddressjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressjTextField1ActionPerformed(evt);
            }
        });

        PhonejTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhonejTextField2ActionPerformed(evt);
            }
        });

        TimingsjTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimingsjTextField5ActionPerformed(evt);
            }
        });

        savejButton1.setText("Save");
        savejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButton1ActionPerformed(evt);
            }
        });

        SearchjButton2.setText("Search");
        SearchjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchjButton2ActionPerformed(evt);
            }
        });

        UpdatejButton3.setText("Update");
        UpdatejButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatejButton3ActionPerformed(evt);
            }
        });

        ResetjButton4.setText("Reset");
        ResetjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetjButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddressjLabel1)
                                    .addComponent(PhonejLabel2)
                                    .addComponent(EmailjLabel3)
                                    .addComponent(InchargeNamejLabel4)
                                    .addComponent(TimingsjLabel5))
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(savejButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SearchjButton2)
                                .addGap(2, 2, 2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(UpdatejButton3)
                                .addGap(18, 18, 18)
                                .addComponent(ResetjButton4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(AddressjTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                .addComponent(PhonejTextField2)
                                .addComponent(EmailjTextField3)
                                .addComponent(InchargeNamejTextField4)
                                .addComponent(TimingsjTextField5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(ErrorjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddressjLabel1)
                            .addComponent(AddressjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhonejLabel2)
                            .addComponent(PhonejTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailjLabel3)
                            .addComponent(EmailjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(InchargeNamejLabel4))
                    .addComponent(InchargeNamejTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimingsjLabel5)
                    .addComponent(TimingsjTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savejButton1)
                    .addComponent(SearchjButton2)
                    .addComponent(UpdatejButton3)
                    .addComponent(ResetjButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(ErrorjLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddressjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressjTextField1ActionPerformed

    private void PhonejTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhonejTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhonejTextField2ActionPerformed

    private void TimingsjTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimingsjTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimingsjTextField5ActionPerformed

    private void UpdatejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatejButton3ActionPerformed
        // TODO add your handling code here:
        if(AddressjTextField1.getText().equals(""))
            ErrorjLabel1.setText("Enter center's address");
        else
            if(PhonejTextField2.getText().equals(""))
            ErrorjLabel1.setText("Enter centre's phone number");
        else
            if(EmailjLabel3.getText().equals(""))
            ErrorjLabel1.setText("Enter centre's email");
        else
            if(InchargeNamejTextField4.getText().equals(""))
            ErrorjLabel1.setText("Enter incharge name");
        else
            if(TimingsjTextField5.getText().equals(""))
            ErrorjLabel1.setText("Enter centr's timings number");
        
        else
            {
            cobj.Connect();
            try
            {
                pst = cobj.con.prepareCall("{call prcUpdateCenter(?,?,?,?,?,?)}");
                pst.setLong(1, CenterID);
                pst.setString(2,AddressjTextField1.getText());
                pst.setString(3,PhonejTextField2.getText());
                pst.setString(4,EmailjTextField3.getText());
                pst.setString(5,InchargeNamejTextField4.getText());
                pst.setString(6,TimingsjLabel5.getText());
                
                if(pst.execute()==false)
                    if(pst.getUpdateCount()>0)
                    {
                    ErrorjLabel1.setText("Record updated");
                    AddressjTextField1.setText("");
                    PhonejTextField2.setText("");
                    EmailjTextField3.setText("");
                    InchargeNamejTextField4.setText("");
                    TimingsjTextField5.setText("");
                    }

            }
            catch(Exception ex)
            {
                System.out.print("Error in update"+ex);
            }

cobj.DisConnect();
        }
    }//GEN-LAST:event_UpdatejButton3ActionPerformed

    private void savejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButton1ActionPerformed
if(AddressjTextField1.getText().equals(""))
            ErrorjLabel1.setText("Enter center's address");
        else
            if(PhonejTextField2.getText().equals(""))
            ErrorjLabel1.setText("Enter centre's phone number");
        else
            if(EmailjLabel3.getText().equals(""))
            ErrorjLabel1.setText("Enter centre's email");
        else
            if(InchargeNamejTextField4.getText().equals(""))
            ErrorjLabel1.setText("Enter incharge name");
        else
            if(TimingsjTextField5.getText().equals(""))
            ErrorjLabel1.setText("Enter centr's timings number");
        
        else
            {
            cobj.Connect();
            try
            {
                pst = cobj.con.prepareCall("{call prcInsertCenter(?,?,?,?,?)}");
                pst.setString(1,AddressjTextField1.getText());
                pst.setString(2,PhonejTextField2.getText());
                pst.setString(3,EmailjTextField3.getText());
                pst.setString(4,InchargeNamejTextField4.getText());
                pst.setString(5,TimingsjLabel5.getText());
                
                if(pst.execute()==false)
                    if(pst.getUpdateCount()>0)
                    {
                    ErrorjLabel1.setText("Record Saved");
                    AddressjTextField1.setText("");
                    PhonejTextField2.setText("");
                    EmailjTextField3.setText("");
                    InchargeNamejTextField4.setText("");
                    TimingsjTextField5.setText("");
                    }

            }
            catch(Exception ex)
            {
                System.out.print("Error in save"+ex);
            }

cobj.DisConnect();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_savejButton1ActionPerformed

    private void SearchjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchjButton2ActionPerformed
     if(AddressjTextField1.getText().equals(""))
            ErrorjLabel1.setText("Enter centre's address");
        else
             {
            cobj.Connect();
            try
            {
                pst = cobj.con.prepareStatement("Select * from tbcenter where address=?");
                pst.setString(1,AddressjTextField1.getText());
                    rst = pst.executeQuery();
                    if(rst.next())
                    {
                    ErrorjLabel1.setText("Record Found");
                    CenterID=rst.getLong(1);
                    AddressjTextField1.setText(rst.getString(2).trim());
                    PhonejTextField2.setText(rst.getString(3).trim());
                    EmailjTextField3.setText(rst.getString(4).trim());
                    InchargeNamejTextField4.setText(rst.getString(5).trim());
                    TimingsjTextField5.setText(rst.getString(6).trim());
                    
                    }
else
                    {
                        ErrorjLabel1.setText("Record doesnot exist");
                    }
            }
            catch(Exception ex)
            {
                System.out.print("Error in save"+ex);
            }

cobj.DisConnect();
        }   // TODO add your handling code here:
    }//GEN-LAST:event_SearchjButton2ActionPerformed

    private void ResetjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetjButton4ActionPerformed

                    AddressjTextField1.setText("");
                    PhonejTextField2.setText("");
                    EmailjTextField3.setText("");
                    InchargeNamejTextField4.setText("");
                    TimingsjTextField5.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_ResetjButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CenterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CenterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CenterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CenterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CenterJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressjLabel1;
    private javax.swing.JTextField AddressjTextField1;
    private javax.swing.JLabel EmailjLabel3;
    private javax.swing.JTextField EmailjTextField3;
    private javax.swing.JLabel ErrorjLabel1;
    private javax.swing.JLabel InchargeNamejLabel4;
    private javax.swing.JTextField InchargeNamejTextField4;
    private javax.swing.JLabel PhonejLabel2;
    private javax.swing.JTextField PhonejTextField2;
    private javax.swing.JButton ResetjButton4;
    private javax.swing.JButton SearchjButton2;
    private javax.swing.JLabel TimingsjLabel5;
    private javax.swing.JTextField TimingsjTextField5;
    private javax.swing.JButton UpdatejButton3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton savejButton1;
    // End of variables declaration//GEN-END:variables
}
