/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cvcm;

/**
 *
 * @author kashi
 */
public class CertificateJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CertificateJFrame
     */
    public CertificateJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DosageIDjLabel1 = new javax.swing.JLabel();
        certificatenojLabel2 = new javax.swing.JLabel();
        IssueDatejLabel3 = new javax.swing.JLabel();
        statusjLabel4 = new javax.swing.JLabel();
        dosageIDjComboBox1 = new javax.swing.JComboBox<>();
        issuedatejTextField1 = new javax.swing.JTextField();
        certificateIdjTextField2 = new javax.swing.JTextField();
        statusjTextField3 = new javax.swing.JTextField();
        errorjLabel5 = new javax.swing.JLabel();
        SavejButton1 = new javax.swing.JButton();
        SearchjButton2 = new javax.swing.JButton();
        UpdatejButton3 = new javax.swing.JButton();
        resetjButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DosageIDjLabel1.setText("DosageID");

        certificatenojLabel2.setText("Certificate Number");

        IssueDatejLabel3.setText("Issue Date");

        statusjLabel4.setText("Status");

        dosageIDjComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        SavejButton1.setText("Save");

        SearchjButton2.setText("Search");

        UpdatejButton3.setText("Update");

        resetjButton4.setText("Reset");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(errorjLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(DosageIDjLabel1)
                                .addGap(107, 107, 107))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IssueDatejLabel3)
                                .addGap(101, 101, 101)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(certificatenojLabel2)
                            .addGap(54, 54, 54)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(statusjLabel4)
                        .addGap(125, 125, 125)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statusjTextField3)
                    .addComponent(certificateIdjTextField2)
                    .addComponent(issuedatejTextField1)
                    .addComponent(dosageIDjComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(SavejButton1)
                .addGap(18, 18, 18)
                .addComponent(SearchjButton2)
                .addGap(18, 18, 18)
                .addComponent(UpdatejButton3)
                .addGap(18, 18, 18)
                .addComponent(resetjButton4)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DosageIDjLabel1)
                    .addComponent(dosageIDjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(issuedatejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IssueDatejLabel3))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(certificateIdjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(certificatenojLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusjLabel4)
                    .addComponent(statusjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetjButton4)
                    .addComponent(UpdatejButton3)
                    .addComponent(SearchjButton2)
                    .addComponent(SavejButton1))
                .addGap(70, 70, 70)
                .addComponent(errorjLabel5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CertificateJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CertificateJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CertificateJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CertificateJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CertificateJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DosageIDjLabel1;
    private javax.swing.JLabel IssueDatejLabel3;
    private javax.swing.JButton SavejButton1;
    private javax.swing.JButton SearchjButton2;
    private javax.swing.JButton UpdatejButton3;
    private javax.swing.JTextField certificateIdjTextField2;
    private javax.swing.JLabel certificatenojLabel2;
    private javax.swing.JComboBox<String> dosageIDjComboBox1;
    private javax.swing.JLabel errorjLabel5;
    private javax.swing.JTextField issuedatejTextField1;
    private javax.swing.JButton resetjButton4;
    private javax.swing.JLabel statusjLabel4;
    private javax.swing.JTextField statusjTextField3;
    // End of variables declaration//GEN-END:variables
}
