/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cvcm;
import java.sql.PreparedStatement;
import java.sql.ResultSet;


/**
 *
 * @author kashi
 */
public class CitizenJFrame extends javax.swing.JFrame {
    ConnectionClass cobj=new ConnectionClass();
    PreparedStatement pst;
    ResultSet rst; 
    long CitizenID;

    /**
     * Creates new form CitizenJFrame
     */
    public CitizenJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namejLabel1 = new javax.swing.JLabel();
        fnamejLabel2 = new javax.swing.JLabel();
        addressjLabel3 = new javax.swing.JLabel();
        phonejLabel4 = new javax.swing.JLabel();
        emailjLabel5 = new javax.swing.JLabel();
        aadharnumberjLabel6 = new javax.swing.JLabel();
        dorjLabel7 = new javax.swing.JLabel();
        agejLabel8 = new javax.swing.JLabel();
        genderjLabel9 = new javax.swing.JLabel();
        errorjLabel10 = new javax.swing.JLabel();
        namejTextField1 = new javax.swing.JTextField();
        fnamejTextField2 = new javax.swing.JTextField();
        addressjTextField3 = new javax.swing.JTextField();
        phonejTextField4 = new javax.swing.JTextField();
        emailjTextField5 = new javax.swing.JTextField();
        aadharnumberjTextField6 = new javax.swing.JTextField();
        dorjTextField7 = new javax.swing.JTextField();
        agejTextField8 = new javax.swing.JTextField();
        genderjTextField9 = new javax.swing.JTextField();
        savejButton1 = new javax.swing.JButton();
        searchjButton2 = new javax.swing.JButton();
        updatejButton3 = new javax.swing.JButton();
        resetjButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        namejLabel1.setText("Name");

        fnamejLabel2.setText("Father's Name");

        addressjLabel3.setText("Address");

        phonejLabel4.setText("Phone");

        emailjLabel5.setText("Email");

        aadharnumberjLabel6.setText("Aadhar Number");

        dorjLabel7.setText("Date Of Registeration");

        agejLabel8.setText("Age");

        genderjLabel9.setText("Gender");

        fnamejTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnamejTextField2ActionPerformed(evt);
            }
        });

        genderjTextField9.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                genderjTextField9AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        savejButton1.setText("Save");
        savejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButton1ActionPerformed(evt);
            }
        });

        searchjButton2.setText("Search");
        searchjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButton2ActionPerformed(evt);
            }
        });

        updatejButton3.setText("Update");
        updatejButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButton3ActionPerformed(evt);
            }
        });

        resetjButton4.setText("Reset");
        resetjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetjButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(errorjLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namejLabel1)
                            .addComponent(fnamejLabel2)
                            .addComponent(addressjLabel3)
                            .addComponent(phonejLabel4)
                            .addComponent(emailjLabel5)
                            .addComponent(aadharnumberjLabel6)
                            .addComponent(dorjLabel7)
                            .addComponent(agejLabel8)
                            .addComponent(genderjLabel9))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updatejButton3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fnamejTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                .addComponent(namejTextField1)
                                .addComponent(addressjTextField3)
                                .addComponent(phonejTextField4)
                                .addComponent(emailjTextField5)
                                .addComponent(aadharnumberjTextField6)
                                .addComponent(dorjTextField7)
                                .addComponent(agejTextField8)
                                .addComponent(genderjTextField9)))))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(savejButton1)
                .addGap(35, 35, 35)
                .addComponent(searchjButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(resetjButton4)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namejLabel1)
                    .addComponent(namejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fnamejLabel2)
                    .addComponent(fnamejTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressjLabel3)
                    .addComponent(addressjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phonejLabel4)
                    .addComponent(phonejTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailjLabel5)
                    .addComponent(emailjTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aadharnumberjLabel6)
                    .addComponent(aadharnumberjTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dorjLabel7)
                    .addComponent(dorjTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agejLabel8)
                    .addComponent(agejTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderjLabel9)
                    .addComponent(genderjTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savejButton1)
                    .addComponent(searchjButton2)
                    .addComponent(updatejButton3)
                    .addComponent(resetjButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(errorjLabel10)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnamejTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnamejTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnamejTextField2ActionPerformed

    private void savejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButton1ActionPerformed
if(namejTextField1.getText().equals(""))
            errorjLabel10.setText("Enter name");
        else
            if(fnamejTextField2.getText().equals(""))
            errorjLabel10.setText("Enter father's name");
        else
            if(phonejTextField4.getText().equals(""))
               errorjLabel10.setText("Enter phone number");
        else
            if(addressjTextField3.getText().equals(""))
            errorjLabel10.setText("Enter address");
        else
            if(emailjTextField5.getText().equals(""))
            errorjLabel10.setText("Enter email"); 
      
        else
            if(aadharnumberjTextField6.getText().equals(""))
            errorjLabel10.setText("Enter aadhar number");
        else
            if(dorjTextField7.getText().equals(""))
            errorjLabel10.setText("Enter date of registeration");
        else
            if(agejTextField8.getText().equals(""))
            errorjLabel10.setText("Enter age");
        else
            if(genderjTextField9.getText().equals(""))
            errorjLabel10.setText("Enter gender");
        else
            {
                cobj.Connect();
            try
            {
                pst = cobj.con.prepareCall("{call prcInsertCitizen(?,?,?,?,?,?,?,?,?)}");
                pst.setString(1,namejTextField1.getText());
                pst.setString(2,fnamejTextField2.getText());
                pst.setString(3,addressjTextField3.getText());
                pst.setString(4,phonejTextField4.getText());
                pst.setString(5,emailjTextField5.getText());
                pst.setString(6,aadharnumberjTextField6.getText());
                pst.setString(7,dorjTextField7.getText());
                pst.setString(8,agejTextField8.getText());
                pst.setString(9,genderjTextField9.getText());
                
                
                if(pst.execute()==false)
                    if(pst.getUpdateCount()>0)
                    {
                    errorjLabel10.setText("Record Saved");
                    namejTextField1.setText("");
                    fnamejTextField2.setText("");
                    addressjTextField3.setText("");
                    phonejTextField4.setText("");
                    emailjTextField5.setText("");
                    aadharnumberjTextField6.setText("");
                    dorjTextField7.setText("");
                    genderjTextField9.setText("");
                    agejTextField8.setText("");
                    }

            }
            catch(Exception ex)
            {
                System.out.print("Error in save"+ex);
            }

                cobj.DisConnect();
            }
    
        // TODO add your handling code here:
    }//GEN-LAST:event_savejButton1ActionPerformed

    private void genderjTextField9AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_genderjTextField9AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_genderjTextField9AncestorMoved

    private void searchjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButton2ActionPerformed
     if(aadharnumberjTextField6.getText().equals(""))
            errorjLabel10.setText("Enter aadhar number");
        else
             {
            cobj.Connect();
            try
            {
                pst = cobj.con.prepareStatement("Select * from tbcitizen where AadharNumber=?");
                pst.setString(1,aadharnumberjTextField6.getText());
                    rst = pst.executeQuery();
                    if(rst.next())
                    {
                    errorjLabel10.setText("Record Found");
                    CitizenID=rst.getLong(1);
                        System.out.println(CitizenID);
                    namejTextField1.setText(rst.getString(2).trim());
                    fnamejTextField2.setText(rst.getString(3).trim());
                    addressjTextField3.setText(rst.getString(4).trim());
                    phonejTextField4.setText(rst.getString(5).trim());
                    emailjTextField5.setText(rst.getString(6).trim());
                    aadharnumberjTextField6.setText(rst.getString(7).trim());
                    dorjTextField7.setText(rst.getString(8).trim());
                    agejTextField8.setText(rst.getString(9).trim());
                    genderjTextField9.setText(rst.getString(10).trim());
                    
                    }
                    

            }
            catch(Exception ex)
            {
                System.out.print("Error in search"+ex);
            }

cobj.DisConnect();
        }   // TODO add 
        // TODO add your handling code here:
    }//GEN-LAST:event_searchjButton2ActionPerformed

    private void updatejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButton3ActionPerformed
    if(namejTextField1.getText().equals(""))
            errorjLabel10.setText("Enter name");
        else
            if(fnamejTextField2.getText().equals(""))
            errorjLabel10.setText("Enter father's name");
        else
            if(phonejTextField4.getText().equals(""))
               errorjLabel10.setText("Enter phone number");
        else
            if(addressjTextField3.getText().equals(""))
            errorjLabel10.setText("Enter address");
        else
            if(emailjTextField5.getText().equals(""))
            errorjLabel10.setText("Enter email"); 
      
        else
            if(aadharnumberjTextField6.getText().equals(""))
            errorjLabel10.setText("Enter aadhar number");
        else
            if(dorjTextField7.getText().equals(""))
            errorjLabel10.setText("Enter date of registeration");
        else
            if(agejTextField8.getText().equals(""))
            errorjLabel10.setText("Enter age");
        else
            if(genderjTextField9.getText().equals(""))
            errorjLabel10.setText("Enter gender");
        else
            {
                cobj.Connect();
            try
            {
                pst = cobj.con.prepareCall("{call prcUpdateCitizen(?,?,?,?,?,?,?,?,?,?)}");
                 pst.setLong(1, CitizenID);
                pst.setString(2,namejTextField1.getText());
                pst.setString(3,fnamejTextField2.getText());
                pst.setString(4,addressjTextField3.getText());
                pst.setString(5,phonejTextField4.getText());
                pst.setString(6,emailjTextField5.getText());
                pst.setString(7,aadharnumberjTextField6.getText());
                pst.setString(8,dorjTextField7.getText());
                pst.setString(9,agejTextField8.getText());
                pst.setString(10,genderjTextField9.getText());
                
                
                if(pst.execute()==false)
                    if(pst.getUpdateCount()>0)
                    {
                    errorjLabel10.setText("Record Updated");
                    namejTextField1.setText("");
                    fnamejTextField2.setText("");
                    addressjTextField3.setText("");
                    phonejTextField4.setText("");
                    emailjTextField5.setText("");
                    aadharnumberjTextField6.setText("");
                    dorjTextField7.setText("");
                    genderjTextField9.setText("");
                    agejTextField8.setText("");
                    }

            }
            catch(Exception ex)
            {
                System.out.print("Error in update\n"+ex);
            }

                cobj.DisConnect();
            }
     
        // TODO add your handling code here:
    }//GEN-LAST:event_updatejButton3ActionPerformed

    private void resetjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetjButton4ActionPerformed
                    namejTextField1.setText("");
                    fnamejTextField2.setText("");
                    addressjTextField3.setText("");
                    phonejTextField4.setText("");
                    emailjTextField5.setText("");
                    aadharnumberjTextField6.setText("");
                    dorjTextField7.setText("");
                    genderjTextField9.setText("");
                    agejTextField8.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_resetjButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CitizenJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CitizenJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CitizenJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CitizenJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CitizenJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aadharnumberjLabel6;
    private javax.swing.JTextField aadharnumberjTextField6;
    private javax.swing.JLabel addressjLabel3;
    private javax.swing.JTextField addressjTextField3;
    private javax.swing.JLabel agejLabel8;
    private javax.swing.JTextField agejTextField8;
    private javax.swing.JLabel dorjLabel7;
    private javax.swing.JTextField dorjTextField7;
    private javax.swing.JLabel emailjLabel5;
    private javax.swing.JTextField emailjTextField5;
    private javax.swing.JLabel errorjLabel10;
    private javax.swing.JLabel fnamejLabel2;
    private javax.swing.JTextField fnamejTextField2;
    private javax.swing.JLabel genderjLabel9;
    private javax.swing.JTextField genderjTextField9;
    private javax.swing.JLabel namejLabel1;
    private javax.swing.JTextField namejTextField1;
    private javax.swing.JLabel phonejLabel4;
    private javax.swing.JTextField phonejTextField4;
    private javax.swing.JButton resetjButton4;
    private javax.swing.JButton savejButton1;
    private javax.swing.JButton searchjButton2;
    private javax.swing.JButton updatejButton3;
    // End of variables declaration//GEN-END:variables
}
