/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cvcm;

import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author kashi
 */
public class DosageJFrame extends javax.swing.JFrame {
ConnectionClass cobj=new ConnectionClass();
    PreparedStatement pst;
     ResultSet rst;
     long mid[],cid[],citizenid[],did;
    /**
     * Creates new form Dosage
     */
      public DosageJFrame() {
        initComponents();
        mid = new long[10];
        cid= new long[20];
        citizenid=new long[20];
        
        int index=0;
        cobj.Connect();
        try
        {
           pst=cobj.con.prepareStatement("select CenterID, Address from tbCenter ");
           rst=pst.executeQuery();
           while(rst.next())
           {
               cid[index]=rst.getLong(1);
               index++;
               centerIDjComboBox1.addItem(rst.getString(2));
           }
               
        }
        catch(Exception ex)
        {
           System.out.print("error in populting combo box"+ex);
        }
        cobj.DisConnect();
        
        cobj.Connect();
        try
        {
            index=0;
           pst=cobj.con.prepareStatement("select MedicineID, MedicineName+'-'+CompanyName from tbMedicine ");
           rst=pst.executeQuery();
           while(rst.next())
           {
               mid[index]=rst.getLong(1);
               index++;
               MedIDjComboBox3.addItem(rst.getString(2));
           }
               
        }
        catch(Exception ex)
        {
           System.out.print("error in populting combo box"+ex);
        }
        cobj.DisConnect();
        cobj.Connect();
        try
        {
            index=0;
           pst=cobj.con.prepareStatement("select CitizenID, AadharNumber from tbCitizen ");
           rst=pst.executeQuery();
           while(rst.next())
           {
               citizenid[index]=rst.getLong(1);
               index++;
               CitizenIDjComboBox2.addItem(rst.getString(2));
           }
               
        }
        catch(Exception ex)
        {
           System.out.print("error in populting combo box"+ex);
        }
        cobj.DisConnect();
        
        
    }

    /**
     * Creates new form DosageJFrame
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        CenterIDjLabel1 = new javax.swing.JLabel();
        CitizenidjLabel2 = new javax.swing.JLabel();
        medicineidjLabel3 = new javax.swing.JLabel();
        DOV1jLabel4 = new javax.swing.JLabel();
        time1jLabel5 = new javax.swing.JLabel();
        NextDatejLabel6 = new javax.swing.JLabel();
        DOV2jLabel7 = new javax.swing.JLabel();
        Time2jLabel8 = new javax.swing.JLabel();
        errorjLabel10 = new javax.swing.JLabel();
        centerIDjComboBox1 = new javax.swing.JComboBox<>();
        CitizenIDjComboBox2 = new javax.swing.JComboBox<>();
        MedIDjComboBox3 = new javax.swing.JComboBox<>();
        DOV1jTextField1 = new javax.swing.JTextField();
        time1jTextField2 = new javax.swing.JTextField();
        NextDatejTextField3 = new javax.swing.JTextField();
        DOV2jTextField4 = new javax.swing.JTextField();
        Time2jTextField5 = new javax.swing.JTextField();
        savejButton1 = new javax.swing.JButton();
        searchjButton2 = new javax.swing.JButton();
        updatejButton3 = new javax.swing.JButton();
        resetjButton4 = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CenterIDjLabel1.setText("Center ID");

        CitizenidjLabel2.setText("Citizen ID");

        medicineidjLabel3.setText("Medicine ID");

        DOV1jLabel4.setText("Date Of Vaccination 1");

        time1jLabel5.setText("Time");

        NextDatejLabel6.setText("Next Date");

        DOV2jLabel7.setText("Date Of Vaccination 2");

        Time2jLabel8.setText("Time");

        MedIDjComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedIDjComboBox3ActionPerformed(evt);
            }
        });

        DOV1jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOV1jTextField1ActionPerformed(evt);
            }
        });

        time1jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time1jTextField2ActionPerformed(evt);
            }
        });

        savejButton1.setText("Save");
        savejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButton1ActionPerformed(evt);
            }
        });

        searchjButton2.setText("Search");
        searchjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButton2ActionPerformed(evt);
            }
        });

        updatejButton3.setText("Update");

        resetjButton4.setText("Reset");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(errorjLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Time2jLabel8)
                                    .addComponent(DOV2jLabel7)
                                    .addComponent(NextDatejLabel6)
                                    .addComponent(time1jLabel5)
                                    .addComponent(DOV1jLabel4)
                                    .addComponent(medicineidjLabel3)
                                    .addComponent(CitizenidjLabel2)
                                    .addComponent(CenterIDjLabel1))
                                .addGap(75, 75, 75))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(savejButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchjButton2)
                                .addGap(55, 55, 55)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updatejButton3)
                                .addGap(58, 58, 58)
                                .addComponent(resetjButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(centerIDjComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CitizenIDjComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(MedIDjComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DOV1jTextField1)
                                    .addComponent(time1jTextField2)
                                    .addComponent(NextDatejTextField3)
                                    .addComponent(DOV2jTextField4)
                                    .addComponent(Time2jTextField5))))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CenterIDjLabel1)
                    .addComponent(centerIDjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CitizenidjLabel2)
                    .addComponent(CitizenIDjComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medicineidjLabel3)
                    .addComponent(MedIDjComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DOV1jLabel4)
                    .addComponent(DOV1jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(time1jLabel5)
                    .addComponent(time1jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NextDatejLabel6)
                    .addComponent(NextDatejTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DOV2jLabel7)
                    .addComponent(DOV2jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Time2jLabel8)
                    .addComponent(Time2jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatejButton3)
                    .addComponent(resetjButton4)
                    .addComponent(savejButton1)
                    .addComponent(searchjButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(errorjLabel10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DOV1jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOV1jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOV1jTextField1ActionPerformed

    private void time1jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time1jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_time1jTextField2ActionPerformed

    private void MedIDjComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedIDjComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedIDjComboBox3ActionPerformed

    private void savejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButton1ActionPerformed
if(DOV1jTextField1.getText().equals(""))
            errorjLabel10.setText("enter date of vaccination");
        else 
            if(time1jTextField2.getText().equals(""))
                errorjLabel10.setText("enter time");
        else
                if(NextDatejTextField3.getText().equals(""))
                    errorjLabel10.setText("enter next date");
        
        else
                {
                    cobj.Connect();
                    try
                    {
                      pst=cobj.con.prepareCall("{call prcInsertDosage(?,?,?,?,?,?,?,?)}");
                      pst.setLong(1,cid[centerIDjComboBox1.getSelectedIndex()]);
                      pst.setLong(2,citizenid[CitizenIDjComboBox2.getSelectedIndex()]);
                      pst.setLong(3, mid[MedIDjComboBox3.getSelectedIndex()]);
                     
                      pst.setString(4, DOV1jTextField1.getText());
                      
                      pst.setString(5, time1jTextField2.getText());
                      pst.setString(6, NextDatejTextField3.getText());
                      pst.setString(7, DOV2jTextField4.getText());
                      pst.setString(8, Time2jTextField5.getText());
                      
                      if(pst.execute()==false)
                          if(pst.getUpdateCount()>0)
                          {
                              errorjLabel10.setText("Record Save");
                              DOV1jTextField1.setText("");
                              time1jTextField2.setText("");
                              NextDatejTextField3.setText("");
                              DOV2jTextField4.setText("");
                              Time2jTextField5.setText("");
                              
                              
                          }
                    }
                    catch(Exception ex)
                    {
                       System.out.print("error in save"+ex);
                    }
                    cobj.DisConnect();
                }        // TODO add your handling code here:
    }//GEN-LAST:event_savejButton1ActionPerformed

    private void searchjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButton2ActionPerformed
if(CitizenIDjComboBox2.getSelectedItem().equals(""))
           errorjLabel10.setText("select  aadhar number");
            else
       
                    cobj.Connect();
                    try
                    {
                      pst=cobj.con.prepareStatement("select * from tbDosage where CitizenId=? ");
                      pst.setLong(1, CitizenIDjComboBox2.getSelectedIndex());
                      
                      rst=pst.executeQuery();
                      if(rst.next())
                          {
                              errorjLabel10.setText("Record found");
                               did=rst.getLong(1);
                               centerIDjComboBox1.setSelectedIndex(new Feedback_name().arraysearch(cid,rst.getString(2)));
                              cidjTextField1.setText(rst.getString(3));
                              midjComboBox3.setSelectedIndex(new Feedback_name().arraysearch(mid,rst.getLong(4)));
                             jComboBox1.setSelectedItem(rst.getString(5));
                              d1jTextField1.setText(rst.getString(6));
                              v1jTextField1.setText(rst.getString(7).toUpperCase());
                              t1jTextField5.setText(rst.getString(8));
                              d2jTextField3.setText(rst.getString(9));
                              ndjTextField2.setText(rst.getString(10));
                              t2jTextField4.setText(rst.getString(11));
                              v2jTextField2.setText(rst.getString(12).toUpperCase());
                         }
                      else
                      {
                          errjLabel9.setText("Record does not exits");
                          d1jTextField1.setText("");
                          t1jTextField5.setText("");
                          d2jTextField3.setText("");
                          t2jTextField4.setText("");
                          ndjTextField2.setText("");
                        v1jTextField1.setText("");
                        v2jTextField2.setText("");
                      }
                    }
                    catch(Exception ex)
                    {
                       System.out.print("error in search"+ex);
                    }
                    cobj.disconnect();
                        // TODO add your handling code here:
    }//GEN-LAST:event_searchjButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DosageJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DosageJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DosageJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DosageJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DosageJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CenterIDjLabel1;
    private javax.swing.JComboBox<String> CitizenIDjComboBox2;
    private javax.swing.JLabel CitizenidjLabel2;
    private javax.swing.JLabel DOV1jLabel4;
    private javax.swing.JTextField DOV1jTextField1;
    private javax.swing.JLabel DOV2jLabel7;
    private javax.swing.JTextField DOV2jTextField4;
    private javax.swing.JComboBox<String> MedIDjComboBox3;
    private javax.swing.JLabel NextDatejLabel6;
    private javax.swing.JTextField NextDatejTextField3;
    private javax.swing.JLabel Time2jLabel8;
    private javax.swing.JTextField Time2jTextField5;
    private javax.swing.JComboBox<String> centerIDjComboBox1;
    private javax.swing.JLabel errorjLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel medicineidjLabel3;
    private javax.swing.JButton resetjButton4;
    private javax.swing.JButton savejButton1;
    private javax.swing.JButton searchjButton2;
    private javax.swing.JLabel time1jLabel5;
    private javax.swing.JTextField time1jTextField2;
    private javax.swing.JButton updatejButton3;
    // End of variables declaration//GEN-END:variables
}
