/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cvcm;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author kashi
 */
public class MedicineJFrame extends javax.swing.JFrame {
    ConnectionClass cobj=new ConnectionClass();
    PreparedStatement pst;
    ResultSet rst;
    long MedicineID;

    /**
     * Creates new form MedicineJFrame
     */
    public MedicineJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mednamejLabel1 = new javax.swing.JLabel();
        companynamejLabel2 = new javax.swing.JLabel();
        doijLabel3 = new javax.swing.JLabel();
        doejLabel4 = new javax.swing.JLabel();
        quantityjLabel5 = new javax.swing.JLabel();
        medNamejTextField1 = new javax.swing.JTextField();
        companyNamejTextField2 = new javax.swing.JTextField();
        doijTextField3 = new javax.swing.JTextField();
        doejTextField4 = new javax.swing.JTextField();
        quantityjTextField5 = new javax.swing.JTextField();
        errorjLabel6 = new javax.swing.JLabel();
        savejButton1 = new javax.swing.JButton();
        updatejButton2 = new javax.swing.JButton();
        searchjButton3 = new javax.swing.JButton();
        resetjButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mednamejLabel1.setText("Medicine Name");

        companynamejLabel2.setText("Company Name");

        doijLabel3.setText("Date Of Issue");

        doejLabel4.setText("Date Of Expiry");

        quantityjLabel5.setText("Quantity");

        savejButton1.setText("Save");
        savejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButton1ActionPerformed(evt);
            }
        });

        updatejButton2.setText("Update");
        updatejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButton2ActionPerformed(evt);
            }
        });

        searchjButton3.setText("Search");
        searchjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButton3ActionPerformed(evt);
            }
        });

        resetjButton4.setText("Reset");
        resetjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetjButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(errorjLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updatejButton2)
                    .addComponent(savejButton1))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchjButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resetjButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(quantityjLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doijLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(companynamejLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doejLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mednamejLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doejTextField4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(quantityjTextField5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(doijTextField3))
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(companyNamejTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(medNamejTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mednamejLabel1)
                    .addComponent(medNamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companynamejLabel2)
                    .addComponent(companyNamejTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doijLabel3)
                    .addComponent(doijTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doejLabel4)
                    .addComponent(doejTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityjLabel5)
                    .addComponent(quantityjTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savejButton1)
                    .addComponent(searchjButton3))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetjButton4)
                    .addComponent(updatejButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(errorjLabel6)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButton1ActionPerformed
        if(medNamejTextField1.getText().equals(""))
            errorjLabel6.setText("Enter medicine name");
        else
            if(companyNamejTextField2.getText().equals(""))
            errorjLabel6.setText("Enter company's name");
        else
            if(doijTextField3.getText().equals(""))
               errorjLabel6.setText("Enter date of issue");
        else
            if(doejTextField4.getText().equals(""))
            errorjLabel6.setText("Enter date of expiry");
        else
            if(quantityjTextField5.getText().equals(""))
            errorjLabel6.setText("Enter quantity"); 
      
        else
            {
                cobj.Connect();
            try
            {
                pst = cobj.con.prepareCall("{call prcInsertMedicine(?,?,?,?,?)}");
                pst.setString(1,medNamejTextField1.getText());
                pst.setString(2,companyNamejTextField2.getText());
                pst.setString(3,doijTextField3.getText());
                pst.setString(4,doejTextField4.getText());
                pst.setInt(5,Integer.parseInt(quantityjTextField5.getText()));
                
                
                
                if(pst.execute()==false)
                    if(pst.getUpdateCount()>0)
                    {
                    errorjLabel6.setText("Record saved");
                   medNamejTextField1.setText("");
                   companyNamejTextField2.setText("");
                    doijTextField3.setText("");
                    doejTextField4.setText("");
                    quantityjTextField5.setText("");
                    }

            }
            catch(Exception ex)
            {
                System.out.print("Error in save"+ex);
            }

                cobj.DisConnect();
            }// TODO add your handling code here:
    }//GEN-LAST:event_savejButton1ActionPerformed

    private void searchjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButton3ActionPerformed
if(medNamejTextField1.getText().equals(""))
            errorjLabel6.setText("Enter medicine name");
        else
             {
            cobj.Connect();
            try
            {
                pst = cobj.con.prepareStatement("Select * from tbMedicine where MedicineName=?");
                pst.setString(1,medNamejTextField1.getText());
                    rst = pst.executeQuery();
                    if(rst.next())
                    {
                    errorjLabel6.setText("Record Found");
                    MedicineID =rst.getLong(1);
                    medNamejTextField1.setText(rst.getString(2).trim());
                    companyNamejTextField2.setText(rst.getString(3).trim());
                    doijTextField3.setText(rst.getString(4).trim());
                    doejTextField4.setText(rst.getString(5).trim());
                    quantityjTextField5.setText(rst.getString(6).trim());
                    
                    }

            }
            catch(Exception ex)
            {
                System.out.print("Error in search"+ex);
            }

cobj.DisConnect();
        }           // TODO add your handling code here:
    }//GEN-LAST:event_searchjButton3ActionPerformed

    private void resetjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetjButton4ActionPerformed
        // TODO add your handling code here:
        medNamejTextField1.setText("");
        companyNamejTextField2.setText("");
        doijTextField3.setText("");
        doejTextField4.setText("");
        quantityjTextField5.setText("");
    }//GEN-LAST:event_resetjButton4ActionPerformed

    private void updatejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButton2ActionPerformed
    if(medNamejTextField1.getText().equals(""))
            errorjLabel6.setText("Enter center's address");
        else
            if(companyNamejTextField2.getText().equals(""))
            errorjLabel6.setText("Enter centre's phone number");
        else
            if(doijTextField3.getText().equals(""))
            errorjLabel6.setText("Enter centre's email");
        else
            if(doejTextField4.getText().equals(""))
            errorjLabel6.setText("Enter incharge name");
        else
            if(quantityjTextField5.getText().equals(""))
            errorjLabel6.setText("Enter centr's timings number");
        
        else
            {
            cobj.Connect();
            try
            {
                pst = cobj.con.prepareCall("{call prcUpdateMedicine(?,?,?,?,?,?)}");
                pst.setLong(1, MedicineID);
                pst.setString(2,medNamejTextField1.getText());
                pst.setString(3,companyNamejTextField2.getText());
                pst.setString(4,doijTextField3.getText());
                pst.setString(5,doejTextField4.getText());
                pst.setString(6,quantityjTextField5.getText());
                
                if(pst.execute()==false)
                    if(pst.getUpdateCount()>0)
                    {
                    errorjLabel6.setText("Record updated");
                    medNamejTextField1.setText("");
                    companyNamejTextField2.setText("");
                    doijTextField3.setText("");
                    doejTextField4.setText("");
                    quantityjTextField5.setText("");
                    }

            }
            catch(Exception ex)
            {
                System.out.print("Error in update"+ex);
            }

cobj.DisConnect();
        }    
// TODO add your handling code here:
    }//GEN-LAST:event_updatejButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicineJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicineJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicineJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicineJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicineJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField companyNamejTextField2;
    private javax.swing.JLabel companynamejLabel2;
    private javax.swing.JLabel doejLabel4;
    private javax.swing.JTextField doejTextField4;
    private javax.swing.JLabel doijLabel3;
    private javax.swing.JTextField doijTextField3;
    private javax.swing.JLabel errorjLabel6;
    private javax.swing.JTextField medNamejTextField1;
    private javax.swing.JLabel mednamejLabel1;
    private javax.swing.JLabel quantityjLabel5;
    private javax.swing.JTextField quantityjTextField5;
    private javax.swing.JButton resetjButton4;
    private javax.swing.JButton savejButton1;
    private javax.swing.JButton searchjButton3;
    private javax.swing.JButton updatejButton2;
    // End of variables declaration//GEN-END:variables
}
